export const PRODUCT_FIELD_CHANGE = Symbol('PRODUCT_FIELD_CHANGE');
export const SECTION_SETTING = Symbol('SECTION_SETTING');
export const TOGGLE_SECTION_SETTINGS_SIDEBAR = Symbol('TOGGLE_SECTION_SETTINGS_SIDEBAR');
export const ADD_NEW_SECTION = Symbol('ADD_NEW_SECTION');
export const UPDATE_STATE = Symbol('UPDATE_STATE');
export const UPDATE_DISPLAY_MODE = Symbol('UPDATE_DISPLAY_MODE');

export const UPDATE_PRODUCT_SECTION = Symbol('UPDATE_PRODUCT_SECTION');
export const UPDATE_SECTION_SETTINGS = Symbol('UPDATE_SECTION_SETTINGS');
export const DELETE_PRODUCT_SECTION = Symbol('DELETE_PRODUCT_SECTION');

export const DISABLE_DND = Symbol('DISABLE_DND');
export const ENABLE_DND = Symbol('ENABLE_DND');
