export const PRODUCT_FIELD_CHANGE = Symbol('PRODUCT_FIELD_CHANGE');
export const SECTION_SETTING = Symbol('SECTION_SETTING');
export const TOGGLE_SECTION_SETTINGS_SIDEBAR = Symbol('TOGGLE_SECTION_SETTINGS_SIDEBAR');
export const ADD_NEW_SECTION = Symbol('ADD_NEW_SECTION');
export const UPDATE_STATE = Symbol('UPDATE_STATE');
export const UPDATE_DISPLAY_MODE = Symbol('UPDATE_DISPLAY_MODE');

export const UPDATE_PRODUCT_SECTION = Symbol('UPDATE_PRODUCT_SECTION');
export const UPDATE_SECTION_SETTINGS = Symbol('UPDATE_SECTION_SETTINGS');
export const DELETE_PRODUCT_SECTION = Symbol('DELETE_PRODUCT_SECTION');

export const TOGGLE_PRODUCT_PRICING_MODAL = Symbol('TOGGLE_PRODUCT_PRICING_MODAL');
export const ADD_PRODUCT_PRICING_OPTION = Symbol('ADD_PRODUCT_PRICING_OPTION');
export const SELECT_PRODUCT_PRICING_OPTION = Symbol('SELECT_PRODUCT_PRICING_OPTION');
export const EDIT_PRODUCT_PRICING_OPTION = Symbol('EDIT_PRODUCT_PRICING_OPTION');
export const UPDATE_PRODUCT_PRICING_OPTION = Symbol('UPDATE_PRODUCT_PRICING_OPTION');
export const DELETE_PRODUCT_PRICING_OPTION = Symbol('DELETE_PRODUCT_PRICING_OPTION');

export const TOGGLE_PRODUCT_BACKGROUND_MODAL = Symbol('TOGGLE_PRODUCT_BACKGROUND_MODAL');
export const UPDATE_PRODUCT_SAVING_STATUS = Symbol('UPDATE_PRODUCT_SAVING_STATUS');

export const UPDATE_SHIPPING_METHOD_DETAILS = Symbol('UPDATE_SHIPPING_METHOD_DETAILS');
export const ADD_NEW_SHIPPING_METHOD = Symbol('ADD_NEW_SHIPPING_METHOD');
