export const PRODUCT_FIELD_CHANGE = Symbol('PRODUCT_FIELD_CHANGE');
export const SECTION_SETTING = Symbol('SECTION_SETTING');
export const TOGGLE_SECTION_SETTINGS_SIDEBAR = Symbol('TOGGLE_SECTION_SETTINGS_SIDEBAR');
