
export const APP_INIT = Symbol('APP_INIT');

export const SIGN_UP = Symbol('SIGN_UP');
export const SIGN_UP_SUCCESS = Symbol('SIGN_UP_SUCCESS');
export const SIGN_UP_FAILD = Symbol('SIGN_UP_FAILD');


export const LOGIN = Symbol('LOGIN');
export const LOGIN_SUCCESS = Symbol('LOGIN_SUCCESS');
export const LOGIN_FAILD = Symbol('LOGIN_FAILD');

export const LOGOUT = Symbol('LOGOUT');


export const SIGN_UP_INVALID_FIELDS = Symbol('SIGN_UP_INVALID_FIELDS');
export const LOGIN_INVALID_FIELDS = Symbol('LOGIN_INVALID_FIELDS');


export const PROMO_CODE_ACTIVATE = Symbol('PROMO_CODE_ACTIVATE');
/* Product action types */
export const NEW_PRODUCT_INVALID_FORM = Symbol('NEW_PRODUCT_INVALID_FORM');
export const NEW_PRODUCT_FIELD_UPDATE = Symbol('NEW_PRODUCT_FIELD_UPDATE');

export const PRODUCT_DETAILS_FIELD_UPDATE = Symbol('PRODUCT_DETAILS_FIELD_UPDATE');

export const PRODUCT_CHECKOUT_TEMPLATE_UPDATE = Symbol('PRODUCT_CHECKOUT_TEMPLATE_UPDATE');
export const PRODUCT_PAYMENT_METHOD_UPDATE = Symbol('PRODUCT_PAYMENT_METHOD_UPDATE');
export const PRODUCT_BUMP_SETTING_UPDATE = Symbol('PRODUCT_BUMP_SETTING_UPDATE');
export const PRODUCT_ADVANCE_SETTING_UPDATE = Symbol('PRODUCT_ADVANCE_SETTING_UPDATE');

export const PRODUCT_CHECKOUT_FIELD_UPDATE = Symbol('PRODUCT_CHECKOUT_FIELD_UPDATE');
export const PRODUCT_PAYMENT_FIELD_UPDATE = Symbol('PRODUCT_PAYMENT_FIELD_UPDATE');
export const PRODUCT_BUMP_FIELD_UPDATE = Symbol('PRODUCT_BUMP_FIELD_UPDATE');
export const PRODUCT_SETTING_FIELD_UPDATE = Symbol('PRODUCT_SETTING_FIELD_UPDATE');


export const CREATE_NEW_PRODUCT = Symbol('CREATE_NEW_PRODUCT');
export const PRODUCT_CREATED_SUCCESSFULY = Symbol('PRODUCT_CREATED_SUCCESSFULY');
export const PRODUCT_CREATION_FAILD = Symbol('PRODUCT_CREATION_FAILD');
export const UPDATE_PRODUCT = Symbol('UPDATE_PRODUCT');
export const UPDATE_PRODUCT_SUCCESS = Symbol('UPDATE_PRODUCT_SUCCESS');
export const UPDATE_PRODUCT_FAILD = Symbol('UPDATE_PRODUCT_FAILD');
export const GET_PRODUCT_DETAILS = Symbol('GET_PRODUCT_DETAILS');
export const GET_PRODUCT_SUCCESS = Symbol('GET_PRODUCT_SUCCESS');
export const GET_PRODUCT_FAILD = Symbol('GET_PRODUCT_FAILD');


export const GET_USER_PRODUCTS = Symbol('GET_USER_PRODUCTS');
export const GET_USER_PRODUCTS_SUCCESS = Symbol('GET_USER_PRODUCTS_SUCCESS');
export const GET_USER_PRODUCTS_FAILD = Symbol('GET_USER_PRODUCTS_FAILD');

export const DELETE_USER_PRODUCT = Symbol('DELETE_USER_PRODUCT');
export const DELETE_USER_PRODUCT_SUCCESS = Symbol('DELETE_USER_PRODUCT_SUCCESS');
export const DELETE_USER_PRODUCT_FAILD = Symbol('DELETE_USER_PRODUCT_FAILD');
/* Product action types end */


/* PromoCode actions types */
export const APPLAY_ACCOUNT_PROMOCODE = Symbol('APPLAY_ACCOUNT_PROMOCODE');
export const APPLAY_ACCOUNT_PROMOCODE_SUCCESS = Symbol('APPLAY_ACCOUNT_PROMOCODE_SUCCESS');
export const APPLAY_ACCOUNT_PROMOCODE_FAILD = Symbol('APPLAY_ACCOUNT_PROMOCODE_FAILD');

/* PromoCode actions types ends */

/* files uploading actions  */
export const UPLOAD_FILE = Symbol('UPLOAD_FILE');
export const UPLOAD_FILE_SUCCESS = Symbol('UPLOAD_FILE_SUCCESS');
export const UPLOAD_FILE_FAILD = Symbol('UPLOAD_FILE_FAILD');
/* files uploading actions ends */


/* global action types */
export const TOGGLE_CREATE_PRODUCT_MODALE = Symbol('TOGGLE_CREATE_PRODUCT_MODALE');

export const APP_INITIATION = Symbol('APP_INITIATION');
export const TOGGLE_LOADING = Symbol('TOGGLE_LOADING');

export const API_REQUEST = Symbol('API_REQUEST');

